import json
import sys
import os

if len(sys.argv) != 2:
    print("Error! Provide the path to the the graph file to read from")
    exit(1)

###############################
# Get code for custom node
# with open(os.path.join("assets", "customDataStructures.ts"), 'r') as f:
#     code = f.read()
code = ""

###############################
# Convert the graph to a MDP in GDM-TS
file_path = sys.argv[1]
if not os.path.exists(file_path):
    print("Error! Graph file provided does not exist!")
    exit(1)

with open(file_path, "r") as f:
    G = json.load(f)

id_to_edges = {}
id_to_lvl = {}
nodes = []

code += '/////////////////////////////////////////////\n'
code += '// Generated by exportGraphToGDM_TS.py\n'
code += 'import { Graph } from "./GDM-TS";\n'
code += 'import {CustomNode } from "./customNode";\n'
code += 'import {CustomEdge } from "./customEdge";\n'

code += "\n// ========= Nodes =========\n"
code += "export const AUTO_MDP = new Graph();\n\n"

code += "AUTO_MDP.addNode(new CustomNode('start', 0, 0, false, [], [], -1));\n"
code += "AUTO_MDP.addNode(new CustomNode('death', -1, 0, true, [], [], -1));\n"

# Get max reward
max_r = -1
for N in G['nodes']:
    max_r = max(max_r, N["reward"])

NUM_END_LEVELS = 1

for N in G['nodes']:
    if N["name"] == "start" or N["name"] == "death":
        continue

    if "end" in N["name"]:
        # This is cheating but sue me
        N["level"] = [
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-------------",
            "-Xooooooooooo",
            "XXXXXXXXXXXXX",
        ]

    # depth = id.split("-")[0]
    depth = 1 # TODO: set the depth
    is_terminal = "true" if N["name"] == 'end' else "false"

    name = N["name"]
    reward = (N["reward"] / max_r) - 1
    depth = N["depth"]
    node = f'new CustomNode("{name}", {reward}, 0, {is_terminal}, [], {json.dumps(N["level"])}, {depth})'
    code += f"AUTO_MDP.addNode({node});\n"

code += "\n// ========= Edges =========\n"
for E in G['edges']:
    src = E["src"]
    tgt = E["tgt"]
    link = json.dumps(E["link"])
    P = json.dumps([(tgt, 0.99), ("death", 0.01)])

    e = f'new CustomEdge("{src}", "{tgt}", {P}, {link})'
    code += f'AUTO_MDP.addEdge({e});\n'

PATH = os.path.join("autoMDP.ts")
with open(PATH, "w") as f:
    f.write(code)

print(f"Graph and levels written to: {PATH}")
